# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

# https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows#pull_request
on:
  # PRがオープン、再オープンされた時、PRのヘッドが更新された場合実行
  pull_request:
    types: [ opened, synchronize, reopened ]
    # PRターゲットブランチでフィルターする場合
    # branches: [ master, main, releases/** ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # PRのブランチとターゲットのブランチをマージしてCI
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # JUnitテスト結果レポートを作成
    # https://github.com/marketplace/actions/junit-report-action
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'

    - run: echo ${{ github.workspace }}
    - run: echo $GITHUB_WORKSPACE
    - run: cat ${{ github.workspace }}/settings.xml
    - run: cat README.md
    - run: cat UPDATE.md

    # - name: Publish to GitHub Packages Apache Maven
    #   run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
